name: AmzInsights CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set up config files from examples
        run: |
          cp config/settings_example.yaml config/settings.yaml
          cp config/selectors_example.yaml config/selectors.yaml

      - name: Final Check
        run: echo "AmzInsights build successful!"